# Generated by Django 2.2.3 on 2020-07-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200728_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brandset', to='core.Designer'),
        ),
    ]
