# Generated by Django 2.2.3 on 2020-07-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200728_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
