# Generated by Django 2.2.3 on 2020-07-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_designer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
